<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="6AA194BA0CB3950" name="com.baidu.gameqa.generation.MemberOrderApplyQuickOrderTestCase" tests="1" failures="1" timestamp="19 Aug 2014 06:21:55 GMT" time="0.577" errors="0">
  <testcase name="member_order_applyQuickOrder_case01" time="0.577" classname="com.baidu.gameqa.generation.MemberOrderApplyQuickOrderTestCase">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.baidu.gameqa.Gat.executor.CaseExecutor.invokeMethod(Unknown Source)
	at com.baidu.gameqa.Gat.executor.InterfaceStepsExecutor.executeCase(Unknown Source)
	at com.baidu.gameqa.Gat.executor.CaseExecutor.execute(Unknown Source)
	at com.baidu.gameqa.generation.MemberOrderApplyQuickOrderTestCase.member_order_applyQuickOrder_case01(MemberOrderApplyQuickOrderTestCase.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: net.sf.json.JSONException: JSONObject["order_no"] not found.
	at net.sf.json.JSONObject.getString(JSONObject.java:2092)
	at com.baidu.gameqa.iat.steps.common.ActualResultJSON.getActualresultElement(Unknown Source)
	at com.baidu.gameqa.iat.steps.member.MemberOrderApplyQuickOrderSteps.assertOrderExist(Unknown Source)
	... 32 more
]]>
    </failure>
  </testcase> <!-- member_order_applyQuickOrder_case01 -->
</testsuite> <!-- com.baidu.gameqa.generation.MemberOrderApplyQuickOrderTestCase -->
